[package]
name = "kwed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
codespan-reporting = "0.11"
logos2 = "0.13"
chumsky = "0.9"
indexmap = "2.2.6"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
crossterm = "0.27.0"
base64 = "0.22.1"
unicode-xid = "0.2.4"
serde = { version = "1.0.208", features = ["derive"] }
ron = "0.8.1"
clap = { version = "4.5.16", features = ["derive"] }
ulid = "1.1.3"
