[package]
name = "kwed2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
codespan-reporting = "0.11.1"
logos2 = "0.13.4"
nom = "7.1.3"
nom-supreme = "0.8.0"
